server:
  port: 8520

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seascheng/spring-cloud-demo.git # 必须使用https
          search-paths: config-repo
          username: chengweipeng123@163.com
          password: chengwp123
    bus:
      enabled: true
      trace:
        enabled: true

    rabbitmq:



eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:7071/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
